"use strict";

exports.__esModule = true;
exports["default"] = void 0;
var LEKE_DOMAIN = {
  beikeServerName: 'https://beike.leke.cn',
  casDomain: 'leke.cn,sclass.cn',
  casServerName: 'https://cas.leke.cn',
  chatServerName: 'https://chat.leke.cn',
  classServerName: 'class.leke.cn',
  cloudServerName: 'https://cloud.leke.cn',
  courseServerName: 'https://course.leke.cn',
  crmServerName: 'https://crm.leke.cn',
  diagServerName: 'https://diag.leke.cn',
  eduplanServerName: 'https://eduplan.leke.cn',
  fileServerName: 'https://file.leke.cn',
  fsServerName: 'https://fs.leke.cn',
  helpServerName: 'https://help.leke.cn',
  homeServerName: 'https://home.leke.cn',
  homeworkServerName: 'https://homework.leke.cn',
  incentiveServerName: 'https://incentive.leke.cn',
  indexServerName: 'https://index.leke.cn',
  learnServerName: 'https://learn.leke.cn',
  lekeServerName: 'https://www.leke.cn',
  lessonServerName: 'https://lesson.leke.cn',
  mainDomain: 'leke.cn',
  mallServerName: 'https://mall.leke.cn',
  monitorServerName: 'https://monitor.leke.cn',
  noteServerName: 'https://note.leke.cn',
  noticeServerName: 'https://notice.leke.cn',
  onlineServerName: 'http://onlineclass.leke.cn',
  paikeServerName: 'https://paike.leke.cn',
  paperServerName: 'https://paper.leke.cn',
  payServerName: 'https://pay.leke.cn',
  questionServerName: 'https://question.leke.cn',
  rateServerName: 'https://rate.leke.cn',
  repositoryServerName: 'https://repository.leke.cn',
  resourceServerName: 'https://resource.leke.cn',
  rtmpServerName: 'rtmp://vod1.leke.cn/vod',
  sclassServerName: 'http://www.sclass.cn',
  staticServerName: 'https://static.leke.cn',
  supportServerName: 'https://support.leke.cn',
  tesolServerName: 'http://tesol.sclass.cn',
  tutorServerName: 'https://tutor.leke.cn',
  userServerName: 'https://user.leke.cn',
  videoServerName: 'https://video.leke.cn',
  voiceServerName: 'https://voice.leke.cn',
  wrongtopicServerName: 'https://wrongtopic.leke.cn'
};
var _default = LEKE_DOMAIN;
exports["default"] = _default;